name: Build and Deploy Java Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      run: |
        docker build -t wiki-stream-kafka:latest .
        docker save wiki-stream-kafka:latest > wiki-stream-kafka.tar

    - name: Copy application files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        source: "wiki-stream-kafka.tar,docker-compose.yml"
        target: "/opt/wiki-stream-kafka"

    - name: Deploy application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          cd /opt/wiki-stream-kafka
          docker load < wiki-stream-kafka.tar
          docker-compose down
          docker-compose up -d
          rm wiki-stream-kafka.tar
          echo "Deployment completed successfully"
